baseURL = 'https://pranavc28.github.io/blog'
languageCode = 'en-us'
title = 'Pranav on a Tangent'
theme = 'PaperMod'

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]

[params]
    math = true
    [params.assets]
        favicon = "/favicon.svg"
    
    [params.homeInfoParams]
        Title = "ðŸ‘‹ Welcome to my blog"
        Content = """

Hey! Thanks for visiting :) This is Pranav. I work at Google Labs, building Enterprise AI agents to power Google's workforce for the future.
Gaining interest in RL, self-awareness, and evals. Feel free to DM me, chat, or share feedback!
"""

    [[params.socialIcons]]
        name = "github"
        title = "View Source on Github"
        url = "https://github.com/pranavc28"

    [[params.socialIcons]]
        name = "LinkedIn"
        title = "Connect with me on LinkedIn"
        url = "https://www.linkedin.com/in/thepranavchaudhary/"
